name: Mango App

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: mango-web-app
  AZURE_WEBAPP_PACKAGE_PATH: "./Mango.Web/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "Mango.sln"
  APP_PROJECT_PATH: "Mango.Web"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3

        id: filter
        with:
          filters: |
            mango_web_app:
              - 'Mango.Web/**'
            mango_auth_api:
              - 'Mango.Services.AuthAPI/**'
            mango_coupon_api:
              - 'Mango.Services.CouponAPI/**'
            mango_product_api:
              - 'Mango.Services.ProductAPI/**'
            mango_shopping_cart_api:
              - 'Mango.Services.ShoppingCartAPI/**'

###Web App
      - name: Web App steps start here
        if: steps.filter.outputs.mango_web_app == 'true'
        run: |
            cd Mango.Web
            echo 'Cambios en Web App.'

###Auth API
      - name: Auth API steps start here
        if: steps.filter.outputs.mango_auth_api == 'true'
        run: |
            cd Mango.Services.AuthAPI
            echo 'Cambios en Auth API'

###Coupon API
      - name: Coupon API steps start here
        if: steps.filter.outputs.mango_product_api == 'true'
        run: |
            cd Mango.Services.CouponAPI
            echo 'Cambios en Coupon API'

###Product API
      - name: Product API steps start here
        if: steps.filter.outputs.mango_product_api == 'true'
        run: |
            cd Mango.Services.ProductAPI
            echo 'Cambios en Product API'
