name: Mango App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./Mango.Web/Mango.Web.csproj

      - name: Build
        run: dotnet build ./Mango.Web/Mango.Web.csproj --configuration Release --no-restore 
