name: Mango App

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  #AZURE_WEBAPP_NAME: mango-web-app
  #AZURE_WEBAPP_PACKAGE_PATH: "./Mango.Web/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "Mango.sln"
  #APP_PROJECT_PATH: "Mango.Web"
  PUBLISH_DIR: "./publish"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      web-app: ${{ steps.filter.outputs.mango_web_app }}
      auth-api: ${{ steps.filter.outputs.mango_auth_api }}
      coupon-api: ${{ steps.filter.outputs.mango_coupon_api }}
      product-api: ${{ steps.filter.outputs.mango_product_api }}
      shopping-cart-api: ${{ steps.filter.outputs.mango_shopping_cart_api }}

    steps:
      - uses: dorny/paths-filter@v3

        id: filter
        with:
          filters: |
            mango_web_app:
              - 'Mango.Web/**'
            mango_auth_api:
              - 'Mango.Services.AuthAPI/**'
            mango_coupon_api:
              - 'Mango.Services.CouponAPI/**'
            mango_product_api:
              - 'Mango.Services.ProductAPI/**'
            mango_shopping_cart_api:
              - 'Mango.Services.ShoppingCartAPI/**'

###Build and Test Web App
  build-and-test-web-app:
    needs: changes
    if: ${{ needs.changes.outputs.web-app }}
    name: build-and-test-web-app start here
    runs-on: ubuntu-latest
    steps:
      - env:
          AZURE_WEBAPP_NAME: mango-web-app
          AZURE_WEBAPP_PACKAGE_PATH: "./Mango.Web/publish"
          APP_PROJECT_PATH: "Mango.Web"

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      #- name: Publish
      #  run: dotnet publish ${{ env.APP_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      #- name: Publish Artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: webapp
      #    path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-web-app:
    name: Deploy Web App to Azure
    if: ${{ needs.changes.outputs.web-app }} 
    runs-on: ubuntu-latest
    needs: [build-and-test-web-app]

    steps:
      - name: Download artifact from build job
        run: echo "Download artifact from build job"
        #uses: actions/download-artifact@v4
        #with:
        #  name: webapp
        #  path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      - name: Deploy
        run: echo "Deploy"
        #uses: azure/webapps-deploy@v2
        #with:
        #  app-name: ${{ env.AZURE_WEBAPP_NAME }}
        #  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #  package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
