name: Mango App

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  #AZURE_WEBAPP_NAME: mango-web-app
  #AZURE_WEBAPP_PACKAGE_PATH: "./Mango.Web/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "Mango.sln"
  #APP_PROJECT_PATH: "Mango.Web"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.isWebAppChanged.outputs.value }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3

        id: filter
        with:
          filters: |
            mango_web_app:
              - 'Mango.Web/**'
            mango_auth_api:
              - 'Mango.Services.AuthAPI/**'
            mango_coupon_api:
              - 'Mango.Services.CouponAPI/**'
            mango_product_api:
              - 'Mango.Services.ProductAPI/**'
            mango_shopping_cart_api:
              - 'Mango.Services.ShoppingCartAPI/**'

###Esto es común para todos los despliegues
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: ${{ env.DOTNET_VERSION }}

#      - name: Restore
#        run: dotnet restore ${{ env.SOLUTION_PATH }}

#      - name: Build
#        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

#      - name: Test
#        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal
              

###Web App
      - name: Web App steps start here
        id: isWebAppChanged
        if: steps.filter.outputs.mango_web_app == 'true'
        env:
          AZURE_WEBAPP_NAME: mango-web-app
          AZURE_WEBAPP_PACKAGE_PATH: "./Mango.Web/publish"
          APP_PROJECT_PATH: "Mango.Web"        
        run: |
            cd Mango.Web
            echo 'Cambios en Web App.'
            run: echo "value=true" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy Web App to Azure 
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      - name: Download artifact from build job
        #uses: actions/download-artifact@v4
        #if: steps.isWebAppChanged.output.value == true
      - env:  
          OUTPUT1: ${{ needs.build-and-test.outputs.output1 }}
        run: echo "$OUTPUT1"
